import { Order } from "../types/Order";

export const getAllOrders = async (): Promise<Order[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          orderNumber: "#ORD001",
          date: "2025-04-01",
          customerName: "John Doe",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 150.75,
        },
        {
          orderNumber: "#ORD002",
          date: "2025-04-02",
          customerName: "Jane Smith",
          paymentStatus: "Pending",
          orderStatus: "Ready",
          total: 200.0,
        },
        {
          orderNumber: "#ORD003",
          date: "2025-04-03",
          customerName: "Alice Johnson",
          paymentStatus: "Failed",
          orderStatus: "Cancelled",
          total: 120.5,
        },
        {
          orderNumber: "#ORD004",
          date: "2025-04-04",
          customerName: "Bob Brown",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 300.0,
        },
        {
          orderNumber: "#ORD005",
          date: "2025-04-05",
          customerName: "Charlie Green",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 450.25,
        },
        {
          orderNumber: "#ORD006",
          date: "2025-04-06",
          customerName: "Diana White",
          paymentStatus: "Pending",
          orderStatus: "Ready",
          total: 180.0,
        },
        {
          orderNumber: "#ORD007",
          date: "2025-04-07",
          customerName: "Ethan Black",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 220.0,
        },
        {
          orderNumber: "#ORD008",
          date: "2025-04-08",
          customerName: "Fiona Blue",
          paymentStatus: "Failed",
          orderStatus: "Cancelled",
          total: 99.99,
        },
        {
          orderNumber: "#ORD009",
          date: "2025-04-09",
          customerName: "George Yellow",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 275.0,
        },
        {
          orderNumber: "#ORD010",
          date: "2025-04-10",
          customerName: "Hannah Red",
          paymentStatus: "Pending",
          orderStatus: "Ready",
          total: 310.0,
        },
        {
          orderNumber: "#ORD011",
          date: "2025-04-11",
          customerName: "Ian Purple",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 400.0,
        },
        {
          orderNumber: "#ORD012",
          date: "2025-04-12",
          customerName: "Jack Orange",
          paymentStatus: "Failed",
          orderStatus: "Cancelled",
          total: 150.0,
        },
        {
          orderNumber: "#ORD013",
          date: "2025-04-13",
          customerName: "Karen Pink",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 500.0,
        },
        {
          orderNumber: "#ORD014",
          date: "2025-04-14",
          customerName: "Liam Gray",
          paymentStatus: "Pending",
          orderStatus: "Ready",
          total: 275.5,
        },
        {
          orderNumber: "#ORD015",
          date: "2025-04-15",
          customerName: "Mia Cyan",
          paymentStatus: "Paid",
          orderStatus: "Shipped",
          total: 350.0,
        },
      ]);
    }, 100);
  });
};
